#!/bin/sh -ex
tmp=$(git-hooks-workdir "$@")
trap 'rm -rf "$tmp"' INT TERM EXIT HUP

cd "$tmp/doc"

notwiki-doc html "/srv/www/htdocs/code/notwiki" .
notwiki-doc gph  "/srv/gopher/notwiki" .
notwiki-mandoc gph utf8 "/srv/gopher/man" .
notwiki-mandoc html html "/srv/www/htdocs/code/man" .
cp "style.css" "/srv/www/htdocs/code"

cd "$tmp"

make release
cp "notwiki-"*".tar.gz" "/srv/www/htdocs/code/notwiki"
cp "notwiki-"*".tar.gz" "/srv/gopher/notwiki"
