.TH NOTMARKDOWN 1
.
.SH NAME
.
.B notmarkdown
- a markdown processor
.
.SH SYNOPSIS
.
.B notmarkdown
format
.I file.md ...
.
.SH DESCRIPTION
.
.B notmarkdown
converts an input markdown file to any of the supported formats:
html (only page content),
gph (the
.IR geomyidae(8)
format),
txt (plain text),
gmi (gemini index files),
ms (troff -ms document),
cat (dump intermediate format).
.
.SH EXAMPLES
.
.EX
To convert an entire website from markdown to multiple formats at once:
.Bd -literal
find . -name "*.md" -print -exec sh -euc '
  notmarkdown "$0" html >${0%.md}.html
  notmarkdown "$0" gph >${0%.md}.gph
  notmarkdown "$0" txt >${0%.md}.txt
  notmarkdown "$0" gmi >${0%.md}.gmi
  notmarkdown "$0" ms | troff -ms | tr2post | ps2pdf >${0%.md}.pdf
\&' {} \e;
.EE
.
.PP
To convert subdomains (such as HTTP vHosts) to subdirectories:
.
.EX
$ cd /var/gopher
$ export SERVER=wiki.example.com PREFIX=wiki
$ notmarkdown gph wiki/index.md >wiki/index.gph
$ export SERVER=news.example.com PREFIX=news
$ notmarkdown gph news/index.md >news/index.gph
.EE
.
.SH SEE ALSO
.
.IR notmarkdown(5),
.IR geomyidae(8)
