.TH NOTMARKDOWN 5
.
.SH NAME
.
.B notmarkdown
- a subset of markdown used by notwiki
.
.SH DESCRIPTION
.
The
.B notmarkdown
format is a subset of the markdown format, with fewer, and unambiguous 
conversion rules:
.
.SS Block Syntax
.
.B Notmarkdown
is a line-based syntax, with 
or headings.
The following syntax occurences provoke switching from the current block to a
new block:
.
.BL -bullet -width 0n
.
.IT
Empty lines:
.PP
.EX
Line of the first block.

Line of the second block.
.EE
.
.PP
Lines with only
.SQ =
or
.SQ - ,
which set the previous block to h1/h2.
.PP
.EX
This is a setext-style heading
==============================
This is part of the paragraph, there may be a
blank line above.
.EE
.
.SS Special Patterns
.
These patterns are matched at line start, opening a new block:
.
.BL -tag -width 14n
.
.IT Ic * No / Ic - No / Ic +
Unordered lists.
Any space before, at least one after.
.
.IT Ic 1. No / Ic 2. No / ...
Ordered lists.
Any space before, at least one after.
.
.IT Ic # , Ic ## , Ic ### No ...
Headings.
Any space before, at least one after.
.
.IT Ic [ref]:
Link reference. 
No space before, at least one after.
.
.IT Ic \et No / Ic ```
Consecutive lines starting with a leading tab \[em] as well as lines after
.IC ```
alone on a line until the next
.IC ```
\[em] are literal blocks.
No conversion is done inside the block, and formatting is preserved.
.
.IT Ic >
Quoted text.
Unlike markdown, it cannot contain list or any other block syntax, but support
all inline syntax.
.
.EL
.
.SS Inline syntnax
.
Within each block, these syntax element are matched:
.
.BL -tag -width 14n
.
.IT Ic *text*
Italic text.
.
.IT Ic **text**
Bold text.
.
.IT Ic ***text***.
Bold italic text.
.
.IT Ic [desc](link)
Inline link
.DQ link
with description
.DQ desc .
.
.IT Ic [desc][ref]
Link with description
.DQ desc
refering to
.DQ ref .
.
.IT Ic [[descref]]
Link with description
.DQ descref
refering to
.DQ descref .
.
.IT Ic ![alt][ref]
Image with alt-text
.DQ alt
and refernce
.DQ ref
for source.
.
.IT Ic ![alt](link)
Inline image with alt-text
.DQ alt
and
.DQ link
for source.
.
.SH EXAMPLES
.
The source repository comes with a
.PA doc/index.md
file that is a complete document example.
.
.SH SEE ALSO
.
.IR notmarkdown-gph(5),
.IR notmarkdown-html(5),
.IR http://josuah.net/notwiki/
.
.SH AUTHORS
.
.AN Josuah Demangeon
.AQ Mt me@josuah.net
