#!/bin/sh -eu
export ext="$1" type="$2" src="$3" dst="$4"

find "$src" -name "*.[0-9]" -print -exec sh -ec '
	file=${0#$src}
	mkdir -p "$dst/$file"
	exec >$dst/$file/index.$ext
	cat "$src/head.$ext"
	mandoc -T$type -Ofragment "$src/$file" | ul -t dumb
' {} \;
