.Dd $Mdocdate: October 25 2020$
.Dt NOTWIKI-HTML 1
.Os
.
.Sh NAME
.
.Nm notwiki-html
.Nd a trivial gopher static wiki generator
.
.Sh SYNOPSIS
.
.Nm notwiki-html
.Ar src
.
.Sh DESCRIPTION
.
.Nm
searches for all
.Dq .md
files in
.Pa src
and convert them to
.Pa .html
in the same path within the current directory.
.
.Sh FILES
.
.Bl -tag -width 12n
.
.It Pa src/head.html
File prepended to each converted document.
.
.El
.
.Sh EXAMPLES
.
.Bd -literal
$ cd /var/htdocs/wiki.example.com/
$ notwiki-html ~/wiki-source/
.Ed
.
.Ed
.
.Sh SEE ALSO
.
.Xr notmarkdown 5 ,
.Xr notmarkdown-gph 1 ,
.Xr geomyidae 8
.
.Sh AUTHORS
.
.An Josuah Demangeon
.Aq Mt me@josuah.net
