#!/bin/sh -e
# convert the subdirs passed as argument recursively to either gph or html

u="${0##*/} <file-extension> <dest-dir> <src-dir>..."
ext=${1:?$u} dest=${2:?$u}
shift 2

find "$@" -name "*.md" | while IFS= read -r file; do
	echo "$file"
	mkdir -p "$dest/$(dirname "$file")"
	cp "$file" "$dest/$(dirname "$file")"
	notmarkdown-"$ext" "$file" | cat head.$ext - >"$dest/${file%.md}.$ext"
done
