#!/bin/sh -eu

export src="$1"

find "$src" -name "*.md" -print -exec sh -euc '
	file=${0#$src}
	mkdir -p "$PWD/${file%/*}"
	cp "$src/head.gph" "$PWD/${file%.md}.gph"
	notmarkdown "$src/$file" | notmarkdown-gph >>$PWD/${file%.md}.gph
' {} \;
