#!/bin/sh -eau
u="${0##*/} <file-extension> <dest-dir> <src-dir>..."
ext=${1:?$u} dest=${2:?$u}
shift 2

find "$@" -name "*.md" | while IFS= read -r file; do
	echo "$file" >&2
	mkdir -p "$dest/$(dirname "$file")"
	cp "$file" "$dest/$(dirname "$file")"
	exec >"$dest/${file%.md}.$ext"
	notmarkdown "$file" | notmarkdown-"$ext" | cat head.$ext -
done
