.Dd $Mdocdate: October 25 2020$
.Dt NOTWIKI-GPH 1
.Os
.
.Sh NAME
.
.Nm notwiki-gph
.Nd a trivial gopher static wiki generator
.
.Sh SYNOPSIS
.
.Nm notwiki-gph
.Ar src
.
.Sh DESCRIPTION
.
.Nm
searches for all
.Dq .md
files in
.Pa src
and convert them to
.Pa .gph
in the same path within the current directory.
.
.Sh FILES
.
.Bl -tag -width 12n
.
.It Pa src/head.gph
File prepended to each converted document.
.
.El
.
.Sh EXAMPLES
.
.Pp
Simple use-case that fits most situations.
.
.Bd -literal
$ cd /var/gopher
$ notwiki-gph ~/wiki-source/
.Ed
.
.Pp
Map vHosts to suffix for converting an HTTP website:
.
.Bd -literal
$ cd /var/gopher
$ VHOST=wiki.example.com notwiki-gph ~/wiki.example.com/
$ VHOST=www.example.com notwiki-gph ~/www.example.com/
$ VHOST=video.example.com notwiki-gph ~/video.example.com/
.Ed
.
.Sh SEE ALSO
.
.Xr notmarkdown 5 ,
.Xr notmarkdown-html 1 ,
.Xr geomyidae 8
.
.Sh AUTHORS
.
.An Josuah Demangeon
.Aq Mt me@josuah.net
